# Generated by Django 4.2.3 on 2023-08-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_employeemodel_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manager',
            new_name='ManagerModel',
        ),
    ]
